// Real entity data wired in from the consolidation pipeline.
// Generated by: C:\OpenclawAISE\consolidated\scripts\07-generate-hero-data.ts
//
// Source of truth is the JSON files under _data/generated/.
// This file is a thin typed shim that the hero components import from.
// To refresh the data: re-run Phase 0.B scripts → copy hero-data/*.json here.

import generatedBrokersJson from './generated/brokers.json';
import generatedPropFirmsJson from './generated/prop-firms.json';
import generatedLiveStatsJson from './generated/live-stats.json';

/* ------------------------------------------------------------------
 * Types — kept stable so existing components need no changes.
 * ------------------------------------------------------------------ */

export type RebateRate = {
  accountType: string;
  instrumentClass: 'forex' | 'indices' | 'commodities' | 'crypto' | 'metals';
  ratePerLot: number;
  note?: string;
  _synthesized?: boolean;
};

export type BrokerEntity = {
  type: 'broker';
  slug: string;
  name: string;
  logo: string;             // either a URL, a relative path, or "" (consumer falls back to initials)
  logoColor: string;
  jurisdictions: string[];
  jurisdictionIds: string[];
  platforms: string[];
  minDeposit: number;
  trustScore: number;       // 0-10
  rebateRates: RebateRate[];
  accountTypes: string[];
  defaultAccountType: string;
  lastVerified: string;
  popularityRank: number;
  headquarters: string | null;
  founded: string | null;
  affiliateUrl: string | null;
};

export type PropFirmEntity = {
  type: 'prop-firm';
  slug: string;
  name: string;
  logo: string;
  logoColor: string;
  evaluationModel: string;
  trustScore: number;
  accountSizes: number[];
  pricing: Record<number, { standard: number; discounted: number; additionalRebate: number }>;
  profitSplit: string;
  lastVerified: string;
  popularityRank: number;
  headquarters: string | null;
  founded: string | null;
  affiliateUrl: string | null;
};

export type Entity = BrokerEntity | PropFirmEntity;

/* ------------------------------------------------------------------
 * Raw JSON shape (whatever script 07 produced).
 * ------------------------------------------------------------------ */

type RawBroker = {
  type: 'broker';
  slug: string;
  name: string;
  logo: string | null;
  logoColor: string;
  rating: number;
  minDeposit: number;
  jurisdictions: string[];
  jurisdictionIds: string[];
  platforms: string[];
  accountTypes: string[];
  defaultAccountType: string;
  rebateRates: Array<{ accountType: string; instrumentClass: string; ratePerLot: number; _synthesized?: boolean }>;
  lastVerified: string;
  popularityRank: number;
  headquarters: string | null;
  founded: string | null;
  affiliateUrl: string | null;
};

type RawPropFirm = {
  type: 'prop-firm';
  slug: string;
  name: string;
  logo: string | null;
  logoColor: string;
  rating: number;
  evaluationModel: string;
  accountSizes: number[];
  pricing: Record<string, { standard: number; discounted: number; additionalRebate: number }>;
  profitSplit: string;
  lastVerified: string;
  popularityRank: number;
  headquarters: string | null;
  founded: string | null;
  affiliateUrl: string | null;
};

/* ------------------------------------------------------------------
 * Hydration: turn the raw JSON records into the typed export shape.
 * ------------------------------------------------------------------ */

function isValidBroker(r: RawBroker): boolean {
  // Drop brokers with no name, no logo we can render, or no account types.
  if (!r.name || !r.slug) return false;
  if (!Array.isArray(r.accountTypes) || r.accountTypes.length === 0) return false;
  if (typeof r.rating !== 'number' || r.rating <= 0) return false;
  return true;
}

function hydrateBroker(r: RawBroker): BrokerEntity {
  return {
    type: 'broker',
    slug: r.slug,
    name: r.name,
    logo: r.logo ?? '',
    logoColor: r.logoColor,
    jurisdictions: r.jurisdictions ?? [],
    jurisdictionIds: r.jurisdictionIds ?? [],
    platforms: r.platforms ?? [],
    minDeposit: r.minDeposit ?? 0,
    trustScore: r.rating,
    rebateRates: (r.rebateRates ?? []).map((rr) => ({
      accountType: rr.accountType,
      instrumentClass: (['forex', 'indices', 'commodities', 'crypto', 'metals'].includes(rr.instrumentClass)
        ? rr.instrumentClass
        : 'forex') as RebateRate['instrumentClass'],
      ratePerLot: rr.ratePerLot,
      _synthesized: rr._synthesized,
    })),
    accountTypes: r.accountTypes ?? ['Standard'],
    defaultAccountType: r.defaultAccountType ?? (r.accountTypes?.[0] ?? 'Standard'),
    lastVerified: r.lastVerified ?? new Date().toISOString().slice(0, 10),
    popularityRank: r.popularityRank ?? 999,
    headquarters: r.headquarters,
    founded: r.founded,
    affiliateUrl: r.affiliateUrl,
  };
}

function hydratePropFirm(r: RawPropFirm): PropFirmEntity {
  // Pricing comes back as Record<string, ...> from JSON — convert keys back to numbers.
  const pricing: PropFirmEntity['pricing'] = {};
  for (const [k, v] of Object.entries(r.pricing ?? {})) {
    const nk = Number(k);
    if (!Number.isNaN(nk)) pricing[nk] = v;
  }

  return {
    type: 'prop-firm',
    slug: r.slug,
    name: r.name,
    logo: r.logo ?? '',
    logoColor: r.logoColor,
    evaluationModel: r.evaluationModel ?? '2-step',
    trustScore: r.rating,
    accountSizes: r.accountSizes ?? [10000, 25000, 50000, 100000, 200000],
    pricing,
    profitSplit: r.profitSplit ?? '80% → 90%',
    lastVerified: r.lastVerified ?? new Date().toISOString().slice(0, 10),
    popularityRank: r.popularityRank ?? 999,
    headquarters: r.headquarters,
    founded: r.founded,
    affiliateUrl: r.affiliateUrl,
  };
}

/* ------------------------------------------------------------------
 * Exports consumed by the hero components.
 * ------------------------------------------------------------------ */

const rawBrokers = (generatedBrokersJson as { brokers: RawBroker[] }).brokers;
const rawPropFirms = (generatedPropFirmsJson as { propFirms: RawPropFirm[] }).propFirms;

// Filter to valid brokers only, then sort by trust score descending so the
// most reputable entities are pre-selected in the picker.
export const BROKERS: BrokerEntity[] = rawBrokers
  .filter(isValidBroker)
  .map(hydrateBroker)
  .sort((a, b) => b.trustScore - a.trustScore);

// Validity check for prop firms: non-empty name + at least one account size + rating > 0
export const PROP_FIRMS: PropFirmEntity[] = rawPropFirms
  .filter((r) => r.name && r.slug && (r.accountSizes?.length ?? 0) > 0 && r.rating > 0)
  .map(hydratePropFirm)
  .sort((a, b) => b.trustScore - a.trustScore);

export const LIVE_STATS = generatedLiveStatsJson as {
  totalPaidOutUSD: number;
  activeTradersRightNow: number;
  brokerCount: number;
  propFirmCount: number;
  avgMonthlyCashback: number;
  jurisdictionsCovered?: number;
};

/* ------------------------------------------------------------------
 * Helpers used by components for logo rendering.
 * ------------------------------------------------------------------ */

export function initialsOf(name: string): string {
  const words = name.replace(/[^a-zA-Z0-9 ]/g, ' ').trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return '??';
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return (words[0][0] + words[1][0]).toUpperCase();
}

export function isImageLogo(logo: string | null | undefined): logo is string {
  if (!logo) return false;
  return /^(https?:|\/)/i.test(logo);
}

/**
 * Build the best logo URL chain.
 * Priority: local /logos/ → Clearbit (real company logos) → original URL → null.
 *
 * Returns { primary, fallback } so the component can try Clearbit first,
 * then fall back to Google favicon if Clearbit 404s.
 */
export function bestLogoUrl(logo: string | null | undefined): string | null {
  if (!logo) return null;
  // Local logo files are highest quality — keep them
  if (logo.startsWith('/logos/')) return logo;
  // Google Favicons → upgrade to Favicone (256px, real high-res icons)
  // Google only returns 16x16 despite sz=256 — Favicone returns actual 256x256
  if (logo.includes('google.com/s2/favicons')) {
    const m = logo.match(/domain=([^&]+)/);
    if (m) return `https://favicone.com/${m[1]}?s=256`;
  }
  // Any other http URL, pass through
  if (/^https?:/i.test(logo)) return logo;
  return null;
}

/** Extract the domain from a Google favicon URL for fallback purposes */
export function extractDomain(logo: string | null | undefined): string | null {
  if (!logo) return null;
  const m = logo.match(/domain=([^&]+)/);
  return m ? m[1] : null;
}
