// Real jurisdiction + arc data wired in from the consolidation pipeline.
// Generated by: C:\OpenclawAISE\consolidated\scripts\07-generate-hero-data.ts

import generatedJurisdictionsJson from './generated/jurisdictions.json';
import generatedArcsJson from './generated/arcs.json';

export type Jurisdiction = {
  id: string;
  name: string;
  city: string;
  country: string;
  countryCode?: string;
  lat: number;
  lng: number;
  regulator: string;
  brokerCount: number;
  avgRebatePerLot: number;
  trustScore: number;
  color: string;
};

type RawJurisdiction = {
  id: string;
  name: string;
  city: string;
  country: string;
  countryCode: string;
  lat: number;
  lng: number;
  regulator: string;
  brokerCount: number;
  avgRebatePerLot: number;
  trustScore: number;
  color: string;
};

type RawArc = {
  fromId: string;
  toId: string;
  startLat: number;
  startLng: number;
  endLat: number;
  endLng: number;
  count: number;
  labels: string[];
  color: [string, string];
};

export type GlobeArc = {
  startLat: number;
  startLng: number;
  endLat: number;
  endLng: number;
  color: [string, string];
  label: string;
  count?: number;
};

/* ------------------------------------------------------------------
 * Load + hydrate
 * ------------------------------------------------------------------ */

const rawJurisdictions = (generatedJurisdictionsJson as { jurisdictions: RawJurisdiction[] }).jurisdictions;
const rawArcs = (generatedArcsJson as { arcs: RawArc[] }).arcs;

// Only surface jurisdictions that actually have brokers attached — a globe
// with empty placeholder nodes isn't useful. Falls back to all jurisdictions
// if the filter would leave us with too few.
const populated = rawJurisdictions.filter((j) => j.brokerCount > 0);

export const JURISDICTIONS: Jurisdiction[] = (populated.length >= 6 ? populated : rawJurisdictions).map(
  (j) => ({
    id: j.id,
    name: j.name,
    city: j.city,
    country: j.country,
    countryCode: j.countryCode,
    lat: j.lat,
    lng: j.lng,
    regulator: j.regulator,
    brokerCount: j.brokerCount,
    avgRebatePerLot: j.avgRebatePerLot,
    trustScore: j.trustScore,
    color: j.color,
  })
);

// Collapse the generated arcs into the simpler shape the globe components expect.
// Each arc now carries a multi-broker label (e.g. "IC Markets · Pepperstone · FP Markets").
export const GLOBE_ARCS: GlobeArc[] = rawArcs.map((a) => ({
  startLat: a.startLat,
  startLng: a.startLng,
  endLat: a.endLat,
  endLng: a.endLng,
  color: a.color as [string, string],
  label: a.labels.slice(0, 3).join(' · ') + (a.count > 3 ? ` +${a.count - 3}` : ''),
  count: a.count,
}));
