// Static article metadata for listing pages (avoids loading full markdown)
export interface ArticleMeta {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: string;
  tags?: string[];
}

// Utility to estimate read time from slug (we know these are long-form reviews)
function estimateReadTime(slug: string): string {
  if (slug.includes('-vs-') || slug.includes('-comparison')) return '8 min read';
  if (slug.includes('best-forex-brokers')) return '12 min read';
  return '10 min read';
}

// All article metadata — updated 2026-03-31
export const articlesMeta: ArticleMeta[] = [
  {
    slug: 'aaafx-review',
    title: 'AAAFx Review 2026: Is This ZuluTrade-Powered ECN Broker Worth Your Money?',
    excerpt: 'AAAFx review 2026: HCMC-regulated broker (#4/435), ZuluTrade copy trading, EUR/USD from 0.0 pips, $100 min deposit. 17+ years in business. Full analysis inside.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'acy-securities-review',
    title: 'ACY Securities Review 2026: Is This Aussie Broker a Hidden Gem?',
    excerpt: 'ACY Securities review 2026 — ASIC regulated, spreads from 0.0 pips, MT4/MT5. Honest pros, cons, fees & trading conditions. Read before you sign up.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'activtrades-review',
    title: 'ActivTrades Honest 2026 Review: 25 Years of Excellence or Stagnation?',
    excerpt: 'ActivTrades review 2026: FCA regulated (434413), ACTIVTrader platform with SmartOrder tools, spreads from 0.50 pips, $1 minimum deposit. 25 years of experience. Is it worth it?',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'admiral-markets-review',
    title: 'Admiral Markets (Admirals) Honest 2026 Review: The MetaTrader Specialist',
    excerpt: 'Admiral Markets (Admirals) 2026 review — FCA, ASIC & CySEC regulated, MT4/MT5 specialist, spreads from 0.0 pips on Zero account. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'avatrade-review',
    title: 'AvaTrade Honest 2026 Review: The 9-Regulator Broker — Safe or Overrated?',
    excerpt: 'AvaTrade 2026 review — Regulated across 9 jurisdictions, fixed spreads from 0.9 pips, AvaProtect risk tool. Honest pros, cons, fees, and whether AvaTrade is worth it in 2026.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'axi-review',
    title: 'Axi Review 2026: Is This Australian Forex Broker Still Worth Your Money?',
    excerpt: 'Axi (formerly AxiTrader) 2026 review — ASIC & FCA regulated, spreads from 0.0 pips, Axi Select funded program. Real license numbers, pros, cons, fees.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'best-forex-brokers-singapore-2026',
    title: 'Top 10 Best Forex Brokers in Singapore 2026 (MAS Regulated & Trusted)',
    excerpt: 'The definitive guide to the best forex brokers in Singapore for 2026. All MAS-regulated, tested by real traders. Spreads, fees, platforms compared.',
    category: 'Rankings',
    date: '2026-03-28',
    readTime: '12 min read',
    tags: ['best-brokers', 'top-10', 'singapore', 'MAS', 'regulation'],
  },
  {
    slug: 'best-forex-brokers-2026',
    title: 'Best Forex Brokers 2026: Top 10 Ranked & Reviewed',
    excerpt: 'Expert-ranked top 10 forex brokers for 2026. Compare spreads, regulation, platforms, and fees. Updated with real data from 70+ broker reviews.',
    category: 'Rankings',
    date: '2026-03-31',
    readTime: '12 min read',
    tags: ['best-brokers', 'top-10', 'rankings', 'regulation'],
  },
  {
    slug: 'best-low-spread-forex-brokers-2026',
    title: 'Best Low Spread Forex Brokers 2026: Cheapest Brokers Ranked',
    excerpt: 'The lowest-spread forex brokers in 2026 ranked by EUR/USD cost. Compare IC Markets, Fusion Markets, Pepperstone, Tickmill, and more. Real spread data and commission breakdowns.',
    category: 'Rankings',
    date: '2026-03-31',
    readTime: '12 min read',
    tags: ['best-brokers', 'low-spread', 'ecn', 'rankings'],
  },
  {
    slug: 'best-ecn-brokers-2026',
    title: 'Best ECN Forex Brokers 2026: Top Brokers with Raw Spreads',
    excerpt: 'The best ECN forex brokers in 2026. Compare True ECN brokers with raw spreads, deep liquidity, and transparent pricing. IC Markets, Pepperstone, Tickmill, and more ranked.',
    category: 'Rankings',
    date: '2026-03-31',
    readTime: '12 min read',
    tags: ['best-brokers', 'ecn', 'low-spread', 'rankings'],
  },
  {
    slug: 'ic-markets-vs-pepperstone',
    title: 'IC Markets vs Pepperstone 2026: Head-to-Head Comparison',
    excerpt: 'IC Markets vs Pepperstone — the ultimate head-to-head comparison for 2026. Compare regulation, spreads, platforms, execution, and fees to find out which ECN broker wins.',
    category: 'Comparison',
    date: '2026-03-31',
    readTime: '8 min read',
    tags: ['ecn', 'low-spread', 'comparison', 'ic-markets', 'pepperstone'],
  },
  {
    slug: 'blackbull-markets-review',
    title: 'BlackBull Markets Review 2026: True ECN Broker With Award-Winning Gold Spreads',
    excerpt: 'BlackBull Markets 2026 review — NZ FMA regulated, true ECN spreads from 0.0 pips, 26,000+ instruments. License numbers, pros, cons, fees, and honest verdict.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'city-index-review',
    title: 'City Index Honest 2026 Review: Is This StoneX-Owned Broker Still a Top Pick?',
    excerpt: 'City Index 2026 review — FCA & ASIC regulated, 13,500+ markets, tight spreads. Honest pros, cons, fees, platforms, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'cmc-markets-review',
    title: 'CMC Markets Honest 2026 Review: Is This London Giant Worth Your Capital?',
    excerpt: 'CMC Markets 2026 review — FCA, ASIC & MAS regulated, 283 forex pairs, spreads from 0.5 pips RAW. Honest pros, cons, fees, platforms, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'darwinex-review',
    title: 'Darwinex Honest 2026 Review: Where Traders Become Fund Managers',
    excerpt: 'Darwinex review 2026: FCA regulated (521888), unique DARWIN investment model, spreads from 0.50 pips. Can you really earn performance fees as a strategy manager?',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'eightcap-review',
    title: 'Eightcap Review 2026: Best Crypto CFD Broker? ASIC-Regulated Expert Analysis',
    excerpt: 'Eightcap 2026 review — ASIC regulated, crypto CFD specialist, prop firm partner. License numbers, real spreads, pros, cons, fees. Is Eightcap legit?',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'etoro-review',
    title: 'eToro Honest 2026 Review: The Copy Trading Giant — But Is It Actually Good?',
    excerpt: 'eToro 2026 review — FCA, CySEC & ASIC regulated, 38M+ users, copy trading. Honest pros, cons, fees, spreads, and whether eToro is worth it for forex in 2026.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
    tags: ['copy-trading', 'social-trading', 'fca', 'beginner-friendly'],
  },
  {
    slug: 'etoro-vs-plus500-comparison',
    title: 'eToro vs Plus500: Which CFD Broker Is Better in 2026? (Honest Comparison)',
    excerpt: 'eToro vs Plus500 head-to-head comparison for 2026. Spreads, fees, platforms, regulation, and honest verdict on which CFD broker is better.',
    category: 'Comparison',
    date: '2026-03-28',
    readTime: '8 min read',
    tags: ['comparison', 'copy-trading', 'cfds', 'fca', 'cysec'],
  },
  {
    slug: 'exness-review',
    title: 'Exness Honest 2026 Review: Is This Instant-Withdrawal Broker the Real Deal?',
    excerpt: 'Exness 2026 review — CySEC & FCA regulated, instant withdrawals, spreads from 0.0 pips, 200+ instruments. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'fbs-review',
    title: 'FBS Honest 2026 Review: The $1 Minimum Deposit Broker — Too Good to Be True?',
    excerpt: 'FBS review 2026: $1 minimum deposit, spreads from 1.0 pips, 1:3000 leverage, regulation (CySEC, ASIC, IFSC). 27M+ traders. Find out if this beginner-friendly broker is legit.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'fp-markets-review',
    title: 'FP Markets Honest 2026 Review: Australia\'s Hidden Gem for Forex Traders?',
    excerpt: 'FP Markets 2026 review — ASIC & CySEC regulated, raw spreads from 0.0 pips, 10,000+ instruments. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
    tags: ['ecn', 'low-spread', 'asic', 'australian-broker'],
  },
  {
    slug: 'fusion-markets-review',
    title: 'Fusion Markets Review 2026: The World\'s Lowest-Cost Forex Broker?',
    excerpt: 'Fusion Markets 2026 review — ASIC regulated, $2.25/lot commission, spreads from 0.07 pips, $0 minimum deposit. Real license numbers, pros, cons, fees.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
    tags: ['ecn', 'low-spread', 'asic', 'australian-broker'],
  },
  {
    slug: 'fxcm-review',
    title: 'FXCM Honest 2026 Review: Can This Comeback Broker Be Trusted?',
    excerpt: 'FXCM 2026 review — FCA & ASIC regulated after major rebuild. Honest look at spreads, platforms, regulation, pros, cons, and whether FXCM is safe in 2026.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'fxpro-review',
    title: 'FxPro Review 2026: 5 Regulations, McLaren F1 Sponsor — But Is It Worth It?',
    excerpt: 'FxPro 2026 review — FCA & CySEC regulated, 5 licenses worldwide, McLaren F1 sponsor, 2M+ accounts. Real license numbers, spreads, fees, pros, cons.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'fxtm-review',
    title: 'FXTM (ForexTime) Honest 2026 Review: Is This Global Broker Still a Strong Contender?',
    excerpt: 'FXTM 2026 review — FCA & CySEC regulated, 250+ instruments, copy trading, competitive spreads. Honest pros, cons, fees, platforms, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'go-markets-review',
    title: 'GO Markets Review 2026: 20 Years of ASIC-Regulated Trading Excellence',
    excerpt: 'GO Markets 2026 review — ASIC regulated since 2006, raw spreads from 0.0 pips, 5 platforms, 20+ year track record. License numbers, pros, cons, fees.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'hf-markets-review',
    title: 'HFM Review 2026: 8 Regulatory Licenses — Is This the Most Regulated Forex Broker?',
    excerpt: 'HFM (formerly HotForex) 2026 review — 8 licenses including FCA, CySEC, ASIC. Zero inactivity fees, spreads from 0.0 pips, 2.5M+ accounts.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'hycm-review',
    title: 'HYCM Honest 2026 Review: Can This 40-Year-Old Broker Still Compete?',
    excerpt: 'HYCM review 2026: Real spread data (EUR/USD from 0.20 pips Raw), regulation (FCA, CySEC, DFSA), fees including the controversial $50 withdrawal fee.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'ic-markets-review',
    title: 'IC Markets Honest 2026 Review: The World\'s Largest True ECN Broker?',
    excerpt: 'IC Markets 2026 review — ASIC regulated, true ECN spreads from 0.0 pips, $3.50 commission. Detailed pros, cons, fees, and who should trade with IC Markets.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
    tags: ['ecn', 'low-spread', 'asic', 'australian-broker'],
  },
  {
    slug: 'ig-review',
    title: 'IG Honest 2026 Review: The UK\'s Oldest CFD Broker — Still the Gold Standard?',
    excerpt: 'IG 2026 review — FCA, ASIC & CFTC regulated, 17,000+ markets, spreads from 0.6 pips. Honest pros, cons, fees, and whether IG is worth trading with in 2026.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'interactive-brokers-review',
    title: 'Interactive Brokers Honest 2026 Review: The Professional\'s Broker — Worth It for Retail?',
    excerpt: 'Interactive Brokers 2026 review — SEC/FINRA/CBI regulated, 2M+ clients, stocks/forex/options/futures. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'ironfx-review',
    title: 'IronFX Honest 2026 Review: Is This Multi-Regulated Broker Worth Your Money?',
    excerpt: 'IronFX review 2026: Real spread data (EUR/USD from 0.10 pips ECN), regulation details (FCA, ASIC, CySEC), honest user reviews.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'moneta-markets-review',
    title: 'Moneta Markets Honest 2026 Review: Is This High-Leverage Broker Worth Your Attention?',
    excerpt: 'Moneta Markets 2026 review — ASIC regulated, 1000:1 leverage, spreads from 0.0 pips, 1000+ instruments. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'oanda-review',
    title: 'OANDA Honest 2026 Review: The OG Forex Broker — Still Relevant?',
    excerpt: 'OANDA 2026 review — CFTC/NFA & FCA regulated, no minimum deposit, transparent pricing. Honest pros, cons, fees, and whether OANDA is worth trading with in 2026.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'octafx-review',
    title: 'OctaFX Honest 2026 Review: The Copy Trading Giant — But Is It Safe?',
    excerpt: 'OctaFX review 2026: Copy trading with 15M+ traders, EUR/USD from 0.70 pips, CySEC regulation (#372/19), zero fees. Full analysis of this popular Asian broker.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'pepperstone-au-review',
    title: 'Pepperstone Australia Honest 2026 Review: The Best Australian Broker?',
    excerpt: 'Pepperstone Australia review 2026: ASIC regulated (AFSL 414531), NAB bank partnership, Razor spreads from 0.19 pips, $3.50/side commission.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
    tags: ['ecn', 'low-spread', 'asic', 'australian-broker', 'pepperstone'],
  },
  {
    slug: 'pepperstone-review',
    title: 'Pepperstone Honest 2026 Review: Is This Australian Forex Broker Still Worth It?',
    excerpt: 'Pepperstone 2026 review — ASIC & FCA regulated, spreads from 0.0 pips, 1200+ instruments. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
    tags: ['ecn', 'low-spread', 'asic', 'fca', 'pepperstone'],
  },
  {
    slug: 'pepperstone-vs-icmarkets-vs-ig',
    title: 'Pepperstone vs IC Markets vs IG: Which Is the Best Forex Broker in 2026?',
    excerpt: 'Pepperstone vs IC Markets vs IG — a head-to-head comparison of the top 3 brokers in 2026. Spreads, regulation, platforms, fees, and who should pick which.',
    category: 'Comparison',
    date: '2026-03-28',
    readTime: '8 min read',
    tags: ['ecn', 'low-spread', 'comparison', 'pepperstone', 'ic-markets', 'ig'],
  },
  {
    slug: 'plus500-review',
    title: 'Plus500 Honest 2026 Review: Is This CFD Giant Right for You?',
    excerpt: 'Plus500 2026 review — FCA & CySEC regulated, 2,800+ CFDs, proprietary platform. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'roboforex-review',
    title: 'RoboForex Honest 2026 Review: Offshore Powerhouse or Regulatory Risk?',
    excerpt: 'RoboForex review 2026: 1:2000 leverage, R StocksTrader with 12,000+ instruments, ECN spreads from 0.10 pips. Offshore-regulated (FSC Belize). Is it safe?',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'saxo-bank-review',
    title: 'Saxo Bank Honest 2026 Review: The Premium Danish Bank — Worth the Price?',
    excerpt: 'Saxo Bank 2026 review — FCA, FINMA & MAS regulated, 70,000+ instruments, spreads from 0.4 pips. Honest pros, cons, fees, and whether Saxo Bank is worth it.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'saxo-bank-vs-interactive-brokers-comparison',
    title: 'Saxo Bank vs Interactive Brokers: The Ultimate Professional Broker Comparison (2026)',
    excerpt: 'Saxo Bank vs Interactive Brokers comparison for 2026. Fees, platforms, instruments, regulation — everything professionals need to choose the right broker.',
    category: 'Comparison',
    date: '2026-03-28',
    readTime: '8 min read',
  },
  {
    slug: 'spreadex-review',
    title: 'Spreadex Review 2026: The UK\'s Only Sports + Financial Spread Betting Broker',
    excerpt: 'Spreadex 2026 review — FCA regulated since 1999, sports + financial spread betting from one account, tax-free profits. License numbers, spreads, pros, cons.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'swissquote-review',
    title: 'Swissquote Honest 2026 Review: Is Switzerland\'s Premier Bank-Broker Worth the Premium?',
    excerpt: 'Swissquote 2026 review — Swiss banking licence, FINMA regulated, 3M+ products, multi-asset. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'thinkmarkets-review',
    title: 'ThinkMarkets Honest 2026 Review: 5 Licenses, $0 Deposit, But Is It Actually Good?',
    excerpt: 'ThinkMarkets review 2026: FCA, ASIC, CySEC, FSCA, FSA regulated. ThinkTrader platform, spreads from 0.80 pips, $0 minimum deposit.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'tickmill-review',
    title: 'Tickmill Honest 2026 Review: The Ultra-Low-Cost ECN Broker',
    excerpt: 'Tickmill 2026 review — FCA & CySEC regulated, raw spreads from 0.0 pips, $2 round-turn commission. Honest pros, cons, fees, platforms, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
    tags: ['ecn', 'low-spread', 'fca', 'cysec'],
  },
  {
    slug: 'trade-nation-review',
    title: 'Trade Nation Review 2026: Fixed Spreads That Never Change — Even During News Events',
    excerpt: 'Trade Nation 2026 review — FCA & ASIC regulated, fixed spreads from 1.2 pips, £25 min deposit, Aston Villa sponsor. License numbers, pros, cons.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'vantage-fx-review',
    title: 'Vantage FX (Vantage) Honest 2026 Review: The Low-Commission ECN Broker',
    excerpt: 'Vantage FX review 2026: FCA, ASIC regulated, raw spreads from 0.10 pips, $3/side commission, $50 minimum deposit, TradingView integration.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'xm-group-review',
    title: 'XM Group Honest 2026 Review: Is This Mega-Broker Worth the Hype?',
    excerpt: 'XM Group 2026 review — FCA, ASIC, CySEC regulated, 10M+ clients, ultra-low spreads. Honest pros, cons, fees, and who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-28',
    readTime: '10 min read',
  },
  {
    slug: 'alpari-review',
    title: 'Alpari Review 2026: 28 Years of History, But Is It Still Safe to Trade?',
    excerpt: 'Alpari review 2026: Former FCA broker now offshore-only (SVG). 28-year history, 1:1000 leverage, $50 min deposit. Warning: FCA license revoked 2015. Read before you trade.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'atfx-review',
    title: 'ATFX Review 2026: FCA & CySEC Regulated Broker with Strong African Expansion',
    excerpt: 'ATFX review 2026: FCA (760555) & CySEC (285/15) regulated, Edge account from 0.2 pips, $50 min deposit, MT4/MT5. 1M+ clients. Full spread data & analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'bdswiss-review',
    title: 'BDSwiss Review 2026: ⚠️ High-Risk Offshore Broker — Read Before You Deposit',
    excerpt: 'BDSwiss review 2026: Surrendered CySEC & FCA licenses, now offshore-only. MISA Comoros (T2023244), withdrawal delays reported. Risk rating: HIGH. Full warning.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'blueberry-markets-review',
    title: 'Blueberry Markets Review 2026: Is This Aussie Broker a Hidden Gem?',
    excerpt: 'Blueberry Markets 2026 review — ASIC regulated Australian broker, MT4 & MT5, raw spreads from 0.0 pips. In-depth look at fees, platforms, pros, cons & who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'capital-com-review',
    title: 'Capital.com Review 2026: Is This AI-Powered Broker Worth It?',
    excerpt: 'Capital.com 2026 review — FCA & CySEC regulated, 0% commission on CFDs, AI-driven platform with 6,000+ instruments. Honest pros, cons & who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'colmex-pro-review',
    title: 'Colmex Pro Review 2026: Is This Direct Market Access Broker Worth It?',
    excerpt: 'Colmex Pro 2026 review — CySEC regulated, direct market access (DMA), MT4 & MT5. In-depth look at spreads, fees, platforms, pros, cons & who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'dukascopy-review',
    title: 'Dukascopy Review 2026: Swiss Bank Trading — The Ultimate ECN Broker?',
    excerpt: 'Dukascopy review 2026: FINMA-regulated Swiss bank, EUR/USD from 0.1 pips, JForex 4 platform, CHF 100K deposit protection. Triple-regulated. Full analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'equiti-review',
    title: 'Equiti Review 2026: FCA-Regulated Broker with Strong Middle East & Africa Presence',
    excerpt: 'Equiti review 2026: FCA UK (FRN 741942) regulated, ECN spreads from 0.0 pips, NFA registered, $50 min deposit. Multi-jurisdiction broker. Full analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'errante-review',
    title: 'Errante Review 2026: CySEC-Regulated Broker with 4 Trading Platforms Including TradingView',
    excerpt: 'Errante review 2026: CySEC (#436/23) regulated, MT4/MT5/cTrader/TradingView, $50 min deposit, 120+ instruments. Multi-platform broker analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'forex-com-review',
    title: 'FOREX.com Review 2026: Is This Industry Giant Still the Gold Standard?',
    excerpt: 'FOREX.com 2026 review — FCA, CFTC & ASIC regulated, 800+ instruments, proprietary platform & MT4. Spreads from 0.0 pips. In-depth look at fees, pros, cons & who it\'s best for.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'fxdd-review',
    title: 'FXDD Review 2026: ⚠️ Critical Warning — Withdrawal Blocks & Unverified Sale',
    excerpt: 'FXDD review 2026: CRITICAL — Frozen withdrawals since 2024, unverified 888 Markets sale, TrustPilot 1.6/5. Former MFSA regulated. DO NOT DEPOSIT.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'gbe-brokers-review',
    title: 'GBE Brokers Review 2026: Is This German-Founded Broker Worth It?',
    excerpt: 'GBE Brokers 2026 review — CySEC regulated, ECN spreads from 0.0 pips, MT4 & MT5. In-depth look at fees, platforms, pros, cons & who it suits best.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'grand-capital-review',
    title: 'Grand Capital Review 2026: Is This Budget Broker Worth the Risk?',
    excerpt: 'Grand Capital 2026 review — FinaCom member, MT4 & MT5, $10 minimum deposit. In-depth look at spreads, fees, pros, cons & safety. Honest assessment before signing up.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'hantec-markets-review',
    title: 'Hantec Markets Review 2026: 30+ Years of FCA & ASIC Regulated Forex Trading',
    excerpt: 'Hantec Markets review 2026: FCA (326260) & ASIC (326802) regulated since 1990. NDD execution, MT4/MT5, precious metals expertise. Full broker analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'ic-trading-review',
    title: 'IC Trading Review 2026: The IC Markets Spin-Off with FCA, CySEC & ASIC Regulation',
    excerpt: 'IC Trading review 2026: FCA (682232), CySEC (426/22) & ASIC regulated, EUR/USD from 0.0 pips, cTrader available, $200 min deposit. Scalper-friendly ECN broker.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'infinox-review',
    title: 'Infinox Review 2026: FCA-Regulated Broker with $1 Minimum Deposit & IX Social Copy Trading',
    excerpt: 'Infinox review 2026: FCA (#501178) regulated, $1 min deposit, ECN from 0.0 pips, 500+ stock CFDs, IX Social copy trading. London-based broker analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'justmarkets-review',
    title: 'JustMarkets Review 2026: Offshore Broker with CySEC License & 1:1000 Leverage',
    excerpt: 'JustMarkets review 2026: CySEC (#404/22) regulated, FSA Seychelles (SD088), $1 min deposit, 1:1000 leverage, MT4/MT5. African & Asian market broker.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'libertex-review',
    title: 'Libertex Review 2026: CySEC-Regulated CFD Broker with Commission-Free Stock Investing',
    excerpt: 'Libertex review 2026: CySEC (#164/12) regulated since 2012, commission-free stock investing, MT4/MT5, $100 min deposit, 40+ crypto. F1 & Bayern sponsor.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'litefinance-review',
    title: 'LiteFinance Review 2026: 20+ Year Offshore Broker — Is It Still Worth Trading?',
    excerpt: 'LiteFinance review 2026: 20+ years operating, offshore-only (SVG/Marshall Islands), 1:1000 leverage, 600+ instruments, copy trading. CySEC license withdrawn.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'm4markets-review',
    title: 'M4Markets Review 2026: Ultra-High Leverage Offshore Broker with $5 Minimum Deposit',
    excerpt: 'M4Markets review 2026: FSA Seychelles (SD025) regulated, 1:2000 leverage, $5 min deposit, 80+ forex pairs, MT4/MT5. Emerging market broker analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'markets-com-review',
    title: 'Markets.com Review 2026: CySEC-Regulated CFD Broker with 2,200+ Instruments & Thematic Blends',
    excerpt: 'Markets.com review 2026: CySEC (#092/08) regulated, 2,200+ CFDs, thematic blends, TradingView, $200 min deposit, 4.7M users. Full broker analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'multibank-group-review',
    title: 'MultiBank Group Review 2026: Multi-Regulated Broker with 20,000+ Stock CFDs',
    excerpt: 'MultiBank Group review 2026: ASIC (#416635), DFSA, BaFin regulated, 20,000+ stock CFDs, ECN from 0.0 pips, $50 min deposit. Dubai-based global broker.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'naga-review',
    title: 'NAGA Review 2026: Publicly Listed Social Trading Broker with CySEC Regulation',
    excerpt: 'NAGA review 2026: Frankfurt-listed (A161NR), CySEC (#204/13) regulated, 1,000+ stock CFDs, social trading, $200 min deposit. Fintech broker analysis.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'nordfx-review',
    title: 'NordFX Review 2026: Is This Budget Broker Still Worth Your Attention?',
    excerpt: 'NordFX review 2026 — VFSC & CySEC regulated, MT4 & MT5, low minimum deposit. Honest pros, cons, fees & trading conditions. Read before signing up.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'orbex-review',
    title: 'Orbex Review 2026: CySEC & FSC Regulated Broker with Raw Spreads from 0.0 Pips',
    excerpt: 'Orbex review 2026 — CySEC & FSC regulated, MT4 & MT5, spreads from 0.0 pips. Honest pros, cons, fees & trading conditions. Read before signing up.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'scope-markets-review',
    title: 'Scope Markets Review 2026: FCA & CMA Regulated Broker — Is It Worth Your Time?',
    excerpt: 'Scope Markets review 2026 — FCA & CMA regulated, MT4 & MT5, competitive spreads. Honest pros, cons, fees & trading conditions. Read before signing up.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'strifor-review',
    title: 'Strifor Review 2026: ⚠️ New Mauritius Broker — Limited Regulation & Low Trust Scores',
    excerpt: 'Strifor review 2026: FSC Mauritius (#GB23202670), new broker (~2022), WikiFX 1.99/10, MT5 only, commission-based pricing. Low trust. Read before depositing.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'taurex-review',
    title: 'Taurex Review 2026: Dual FCA & CySEC Regulated Broker with Competitive Raw Spreads',
    excerpt: 'Taurex review 2026: FCA (#688456) & CySEC (#395/20) dual-regulated, EUR/USD from 0.0 pips, $100 min deposit, London HQ. Rebranded from Zenfinex.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'tmgm-review',
    title: 'TMGM Review 2026: ASIC-Regulated Broker with 12,000+ Instruments',
    excerpt: 'TMGM review 2026 — ASIC & VFSC regulated, MT4 & MT5, spreads from 0.0 pips, 12,000+ instruments. Honest pros, cons, fees & trading conditions. Read now.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'tradeview-markets-review',
    title: 'Tradeview Markets Review 2026: CIMA-Regulated ECN Broker with Ultra-Tight Spreads',
    excerpt: 'Tradeview Markets review 2026 — CIMA regulated, MT4/MT5/cTrader, ultra-tight ECN spreads. Honest pros, cons, fees & trading conditions. Read before signing up.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'triomarkets-review',
    title: 'TrioMarkets Review 2026: CySEC-Regulated Broker with Competitive Spreads',
    excerpt: 'TrioMarkets review 2026 — CySEC regulated, MT4 & MT5, competitive spreads. Honest pros, cons, fees & trading conditions. Read before signing up.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'vt-markets-review',
    title: 'VT Markets Review 2026: ⚠️ ASIC-Regulated Broker with Deteriorating Trust Scores',
    excerpt: 'VT Markets review 2026: ASIC (AFSL 517071) regulated, but rapid trust decline in 2026. Account deletion & withdrawal complaints. Read before trading.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
  {
    slug: 'windsor-brokers-review',
    title: 'Windsor Brokers Review 2026: One of the Oldest Forex Brokers — Still Relevant?',
    excerpt: 'Windsor Brokers review 2026 — CySEC & FSC regulated since 1988. Spreads, platforms, pros, cons & fees. One of the oldest forex brokers. Read before signing up.',
    category: 'Broker Reviews',
    date: '2026-03-31',
    readTime: '10 min read',
  },
];

// Get all unique categories
export function getCategories(): string[] {
  const cats = new Set(articlesMeta.map(a => a.category));
  return ['All', ...Array.from(cats).sort()];
}

// Get articles filtered by category
export function getArticlesByCategory(category: string): ArticleMeta[] {
  if (category === 'All') return articlesMeta;
  return articlesMeta.filter(a => a.category === category);
}

// Get related articles: same category first, then by shared tags, then by date (deterministic)
export function getRelatedArticles(slug: string, category: string): ArticleMeta[] {
  const others = articlesMeta.filter(a => a.slug !== slug);
  const current = articlesMeta.find(a => a.slug === slug);
  const currentTags = current?.tags || [];

  // Score each article for relevance
  const scored = others.map(article => {
    let score = 0;
    // Same category = strong signal
    if (article.category === category) score += 10;
    // Shared tags = moderate signal
    if (currentTags.length > 0 && article.tags) {
      const shared = article.tags.filter(t => currentTags.includes(t));
      score += shared.length * 3;
    }
    // Recency bonus (newer articles slightly preferred)
    const daysSinceEpoch = new Date(article.date).getTime() / 86400000;
    score += daysSinceEpoch * 0.001;
    return { article, score };
  });

  // Sort by score descending, then by date descending (deterministic)
  scored.sort((a, b) => b.score - a.score || new Date(b.article.date).getTime() - new Date(a.article.date).getTime());

  return scored.slice(0, 3).map(s => s.article);
}
