export interface RankedBroker {
  id: string;
  rank: number;
  name: string;
  logo: string;
  rating: number;
  score: number;
  minSpread: string;
  maxLeverage: string;
  minDeposit: number;
  regulators: string[];
  established: number;
  specialties: string[];
}

export const rankedBrokers: Record<string, RankedBroker[]> = {
  overall: [
    {
      id: "ic-markets",
      rank: 1,
      name: "IC Markets",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.6,
      score: 96,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 200,
      regulators: ["ASIC", "CySEC", "FSA"],
      established: 2007,
      specialties: ["ECN Trading", "Raw Spreads", "Fast Execution"]
    },
    {
      id: "fp-markets",
      rank: 2,
      name: "FP Markets",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.4,
      score: 94,
      minSpread: "0.1 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["ASIC", "CySEC"],
      established: 2005,
      specialties: ["Multi-Platform", "Copy Trading", "VPS Hosting"]
    },
    {
      id: "pepperstone",
      rank: 3,
      name: "Pepperstone",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.2,
      score: 92,
      minSpread: "0.0 pips",
      maxLeverage: "1:400",
      minDeposit: 0,
      regulators: ["ASIC", "FCA", "CySEC", "BaFin"],
      established: 2010,
      specialties: ["TradingView", "Smart Tools", "Social Trading"]
    },
    {
      id: "xm-group",
      rank: 4,
      name: "XM Group",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.0,
      score: 90,
      minSpread: "1.0 pips",
      maxLeverage: "1:888",
      minDeposit: 5,
      regulators: ["CySEC", "IFSC", "ASIC"],
      established: 2009,
      specialties: ["Low Deposit", "Bonuses", "Education"]
    },
    {
      id: "oanda",
      rank: 5,
      name: "OANDA",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.8,
      score: 88,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 0,
      regulators: ["CFTC", "NFA", "FCA", "ASIC"],
      established: 1996,
      specialties: ["Transparency", "API Access", "Advanced Charts"]
    },
    {
      id: "forex-com",
      rank: 6,
      name: "Forex.com",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.6,
      score: 86,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 100,
      regulators: ["CFTC", "NFA", "FCA"],
      established: 2001,
      specialties: ["DMA Pricing", "Research", "US Regulated"]
    },
    {
      id: "ig-group",
      rank: 7,
      name: "IG Group",
      logo: "https://images.pexels.com/photos/6802049/pexels-photo-6802049.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.4,
      score: 84,
      minSpread: "0.6 pips",
      maxLeverage: "1:30",
      minDeposit: 250,
      regulators: ["FCA", "ASIC", "MAS"],
      established: 1974,
      specialties: ["17K+ Markets", "Charting", "Risk Management"]
    },
    {
      id: "plus500",
      rank: 8,
      name: "Plus500",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.2,
      score: 82,
      minSpread: "0.7 pips",
      maxLeverage: "1:30",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC", "MAS"],
      established: 2008,
      specialties: ["User-Friendly", "No Commission", "Mobile Trading"]
    },
    {
      id: "etoro",
      rank: 9,
      name: "eToro",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.0,
      score: 80,
      minSpread: "1.0 pips",
      maxLeverage: "1:30",
      minDeposit: 50,
      regulators: ["CySEC", "FCA", "ASIC"],
      established: 2007,
      specialties: ["Social Trading", "Copy Trading", "Crypto"]
    },
    {
      id: "avatrade",
      rank: 10,
      name: "AvaTrade",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.8,
      score: 78,
      minSpread: "0.9 pips",
      maxLeverage: "1:400",
      minDeposit: 100,
      regulators: ["CBI", "ASIC", "FSA", "FSCA"],
      established: 2006,
      specialties: ["Education", "Multi-Regulated", "Trading Central"]
    },
    {
      id: "exness",
      rank: 11,
      name: "Exness",
      logo: "https://images.pexels.com/photos/7567526/pexels-photo-7567526.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.6,
      score: 76,
      minSpread: "0.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 1,
      regulators: ["CySEC", "FCA", "FSA"],
      established: 2008,
      specialties: ["High Leverage", "Instant Withdrawals", "Low Deposit"]
    },
    {
      id: "admiral-markets",
      rank: 12,
      name: "Admiral Markets",
      logo: "https://images.pexels.com/photos/6802042/pexels-photo-6802042.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.4,
      score: 74,
      minSpread: "0.5 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC"],
      established: 2001,
      specialties: ["MetaTrader Supreme", "Education", "Analytics"]
    },
    {
      id: "fxpro",
      rank: 13,
      name: "FxPro",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.2,
      score: 72,
      minSpread: "0.6 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSCA"],
      established: 2006,
      specialties: ["Multi-Platform", "NDD Execution", "Institutional"]
    },
    {
      id: "tickmill",
      rank: 14,
      name: "Tickmill",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.0,
      score: 70,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSA"],
      established: 2014,
      specialties: ["Raw Spreads", "ECN", "Institutional Liquidity"]
    },
    {
      id: "hotforex",
      rank: 15,
      name: "HotForex",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.8,
      score: 68,
      minSpread: "1.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 5,
      regulators: ["CySEC", "FSA", "FSCA"],
      established: 2010,
      specialties: ["High Leverage", "Bonuses", "Copy Trading"]
    },
    {
      id: "fxtm",
      rank: 16,
      name: "FXTM",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.6,
      score: 66,
      minSpread: "1.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FCA", "FSA"],
      established: 2011,
      specialties: ["Education", "Copy Trading", "Micro Accounts"]
    },
    {
      id: "alpari",
      rank: 17,
      name: "Alpari",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.4,
      score: 64,
      minSpread: "0.6 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSA", "CySEC"],
      established: 1998,
      specialties: ["PAMM Accounts", "Social Trading", "Analytics"]
    },
    {
      id: "roboforex",
      rank: 18,
      name: "RoboForex",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.2,
      score: 62,
      minSpread: "0.0 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FSC"],
      established: 2009,
      specialties: ["CopyFX", "R Trader", "Analytics"]
    },
    {
      id: "instaforex",
      rank: 19,
      name: "InstaForex",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.0,
      score: 60,
      minSpread: "3.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSC", "CySEC"],
      established: 2007,
      specialties: ["Contests", "Bonuses", "ForexCopy"]
    },
    {
      id: "fbs",
      rank: 20,
      name: "FBS",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 5.8,
      score: 58,
      minSpread: "0.5 pips",
      maxLeverage: "1:3000",
      minDeposit: 1,
      regulators: ["CySEC", "IFSC"],
      established: 2009,
      specialties: ["High Leverage", "Bonuses", "Mobile Trading"]
    }
  ],
  spreads: [
    {
      id: "ic-markets",
      rank: 1,
      name: "IC Markets",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.6,
      score: 98,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 200,
      regulators: ["ASIC", "CySEC", "FSA"],
      established: 2007,
      specialties: ["True ECN", "Raw Spreads", "Institutional Liquidity"]
    },
    {
      id: "pepperstone",
      rank: 2,
      name: "Pepperstone",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.2,
      score: 96,
      minSpread: "0.0 pips",
      maxLeverage: "1:400",
      minDeposit: 0,
      regulators: ["ASIC", "FCA", "CySEC", "BaFin"],
      established: 2010,
      specialties: ["Razor Account", "ECN", "Tight Spreads"]
    },
    {
      id: "tickmill",
      rank: 3,
      name: "Tickmill",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.0,
      score: 94,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSA"],
      established: 2014,
      specialties: ["Pro Account", "Raw Spreads", "ECN"]
    },
    {
      id: "roboforex",
      rank: 4,
      name: "RoboForex",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.2,
      score: 92,
      minSpread: "0.0 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FSC"],
      established: 2009,
      specialties: ["ECN Account", "Raw Spreads", "R Trader"]
    },
    {
      id: "fp-markets",
      rank: 5,
      name: "FP Markets",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.4,
      score: 90,
      minSpread: "0.1 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["ASIC", "CySEC"],
      established: 2005,
      specialties: ["Raw Account", "ECN", "IRESS"]
    },
    {
      id: "exness",
      rank: 6,
      name: "Exness",
      logo: "https://images.pexels.com/photos/7567526/pexels-photo-7567526.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.6,
      score: 88,
      minSpread: "0.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 1,
      regulators: ["CySEC", "FCA", "FSA"],
      established: 2008,
      specialties: ["Zero Account", "Raw Spreads", "Professional"]
    },
    {
      id: "admiral-markets",
      rank: 7,
      name: "Admiral Markets",
      logo: "https://images.pexels.com/photos/6802042/pexels-photo-6802042.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.4,
      score: 86,
      minSpread: "0.5 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC"],
      established: 2001,
      specialties: ["Zero.MT4", "Raw Spreads", "ECN"]
    },
    {
      id: "fbs",
      rank: 8,
      name: "FBS",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 5.8,
      score: 84,
      minSpread: "0.5 pips",
      maxLeverage: "1:3000",
      minDeposit: 1,
      regulators: ["CySEC", "IFSC"],
      established: 2009,
      specialties: ["ECN Account", "Zero Spread", "Raw Pricing"]
    },
    {
      id: "ig-group",
      rank: 9,
      name: "IG Group",
      logo: "https://images.pexels.com/photos/6802049/pexels-photo-6802049.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.4,
      score: 82,
      minSpread: "0.6 pips",
      maxLeverage: "1:30",
      minDeposit: 250,
      regulators: ["FCA", "ASIC", "MAS"],
      established: 1974,
      specialties: ["DMA", "Tight Spreads", "Professional"]
    },
    {
      id: "alpari",
      rank: 10,
      name: "Alpari",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.4,
      score: 80,
      minSpread: "0.6 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSA", "CySEC"],
      established: 1998,
      specialties: ["ECN Account", "Raw Spreads", "Professional"]
    },
    {
      id: "fxpro",
      rank: 11,
      name: "FxPro",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.2,
      score: 78,
      minSpread: "0.6 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSCA"],
      established: 2006,
      specialties: ["cTrader", "Raw Spreads", "ECN"]
    },
    {
      id: "plus500",
      rank: 12,
      name: "Plus500",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.2,
      score: 76,
      minSpread: "0.7 pips",
      maxLeverage: "1:30",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC", "MAS"],
      established: 2008,
      specialties: ["Dynamic Spreads", "No Commission", "Competitive"]
    },
    {
      id: "oanda",
      rank: 13,
      name: "OANDA",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.8,
      score: 74,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 0,
      regulators: ["CFTC", "NFA", "FCA", "ASIC"],
      established: 1996,
      specialties: ["Transparent Pricing", "Fractional Units", "Core Plus"]
    },
    {
      id: "forex-com",
      rank: 14,
      name: "Forex.com",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.6,
      score: 72,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 100,
      regulators: ["CFTC", "NFA", "FCA"],
      established: 2001,
      specialties: ["Commission Account", "DMA", "Institutional"]
    },
    {
      id: "avatrade",
      rank: 15,
      name: "AvaTrade",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.8,
      score: 70,
      minSpread: "0.9 pips",
      maxLeverage: "1:400",
      minDeposit: 100,
      regulators: ["CBI", "ASIC", "FSA", "FSCA"],
      established: 2006,
      specialties: ["Fixed Spreads", "Variable Spreads", "Professional"]
    },
    {
      id: "etoro",
      rank: 16,
      name: "eToro",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.0,
      score: 68,
      minSpread: "1.0 pips",
      maxLeverage: "1:30",
      minDeposit: 50,
      regulators: ["CySEC", "FCA", "ASIC"],
      established: 2007,
      specialties: ["Variable Spreads", "Social Trading", "Copy Trading"]
    },
    {
      id: "xm-group",
      rank: 17,
      name: "XM Group",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.0,
      score: 66,
      minSpread: "1.0 pips",
      maxLeverage: "1:888",
      minDeposit: 5,
      regulators: ["CySEC", "IFSC", "ASIC"],
      established: 2009,
      specialties: ["Standard Account", "Micro Account", "Zero Account"]
    },
    {
      id: "hotforex",
      rank: 18,
      name: "HotForex",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.8,
      score: 64,
      minSpread: "1.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 5,
      regulators: ["CySEC", "FSA", "FSCA"],
      established: 2010,
      specialties: ["Zero Spread", "Premium Account", "VIP"]
    },
    {
      id: "fxtm",
      rank: 19,
      name: "FXTM",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.6,
      score: 62,
      minSpread: "1.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FCA", "FSA"],
      established: 2011,
      specialties: ["Standard Account", "Cent Account", "ECN Zero"]
    },
    {
      id: "instaforex",
      rank: 20,
      name: "InstaForex",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.0,
      score: 60,
      minSpread: "3.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSC", "CySEC"],
      established: 2007,
      specialties: ["Standard Account", "Eurica Account", "Cent Account"]
    }
  ],
  regulation: [
    {
      id: "oanda",
      rank: 1,
      name: "OANDA",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.8,
      score: 98,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 0,
      regulators: ["CFTC", "NFA", "FCA", "ASIC", "IIROC", "MAS"],
      established: 1996,
      specialties: ["Tier 1 Regulation", "Segregated Funds", "Transparency"]
    },
    {
      id: "forex-com",
      rank: 2,
      name: "Forex.com",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.6,
      score: 96,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 100,
      regulators: ["CFTC", "NFA", "FCA", "ASIC", "IIROC"],
      established: 2001,
      specialties: ["US Regulated", "Tier 1", "Institutional Grade"]
    },
    {
      id: "ig-group",
      rank: 3,
      name: "IG Group",
      logo: "https://images.pexels.com/photos/6802049/pexels-photo-6802049.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.4,
      score: 94,
      minSpread: "0.6 pips",
      maxLeverage: "1:30",
      minDeposit: 250,
      regulators: ["FCA", "ASIC", "MAS", "BaFin", "CONSOB"],
      established: 1974,
      specialties: ["FTSE 250", "50+ Years", "Global Regulation"]
    },
    {
      id: "pepperstone",
      rank: 4,
      name: "Pepperstone",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.2,
      score: 92,
      minSpread: "0.0 pips",
      maxLeverage: "1:400",
      minDeposit: 0,
      regulators: ["ASIC", "FCA", "CySEC", "BaFin", "FSCA"],
      established: 2010,
      specialties: ["Multi-Regulated", "Tier 1", "Client Protection"]
    },
    {
      id: "ic-markets",
      rank: 5,
      name: "IC Markets",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.6,
      score: 90,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 200,
      regulators: ["ASIC", "CySEC", "FSA", "FSCA"],
      established: 2007,
      specialties: ["ASIC Regulated", "Segregated Funds", "Compensation"]
    },
    {
      id: "fp-markets",
      rank: 6,
      name: "FP Markets",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.4,
      score: 88,
      minSpread: "0.1 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["ASIC", "CySEC", "FSCA", "SVG FSA"],
      established: 2005,
      specialties: ["ASIC Regulated", "Award Winning", "Client Protection"]
    },
    {
      id: "plus500",
      rank: 7,
      name: "Plus500",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.2,
      score: 86,
      minSpread: "0.7 pips",
      maxLeverage: "1:30",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC", "MAS", "FSCA"],
      established: 2008,
      specialties: ["LSE Listed", "Multi-Regulated", "Segregated Funds"]
    },
    {
      id: "etoro",
      rank: 8,
      name: "eToro",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.0,
      score: 84,
      minSpread: "1.0 pips",
      maxLeverage: "1:30",
      minDeposit: 50,
      regulators: ["CySEC", "FCA", "ASIC", "FINRA"],
      established: 2007,
      specialties: ["Multi-Regulated", "Social Trading", "Investor Protection"]
    },
    {
      id: "admiral-markets",
      rank: 9,
      name: "Admiral Markets",
      logo: "https://images.pexels.com/photos/6802042/pexels-photo-6802042.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.4,
      score: 82,
      minSpread: "0.5 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC", "EFSA"],
      established: 2001,
      specialties: ["20+ Years", "Multi-Regulated", "Client Protection"]
    },
    {
      id: "fxpro",
      rank: 10,
      name: "FxPro",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.2,
      score: 80,
      minSpread: "0.6 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSCA", "SCB"],
      established: 2006,
      specialties: ["Multi-Regulated", "Segregated Funds", "Compensation"]
    },
    {
      id: "xm-group",
      rank: 11,
      name: "XM Group",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.0,
      score: 78,
      minSpread: "1.0 pips",
      maxLeverage: "1:888",
      minDeposit: 5,
      regulators: ["CySEC", "IFSC", "ASIC", "FSA"],
      established: 2009,
      specialties: ["Multi-Regulated", "Global Presence", "Client Protection"]
    },
    {
      id: "avatrade",
      rank: 12,
      name: "AvaTrade",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.8,
      score: 76,
      minSpread: "0.9 pips",
      maxLeverage: "1:400",
      minDeposit: 100,
      regulators: ["CBI", "ASIC", "FSA", "FSCA", "ADGM"],
      established: 2006,
      specialties: ["Multi-Regulated", "Global Licenses", "Segregated Funds"]
    },
    {
      id: "tickmill",
      rank: 13,
      name: "Tickmill",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.0,
      score: 74,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSA", "FSCA"],
      established: 2014,
      specialties: ["FCA Regulated", "Segregated Funds", "Compensation"]
    },
    {
      id: "exness",
      rank: 14,
      name: "Exness",
      logo: "https://images.pexels.com/photos/7567526/pexels-photo-7567526.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.6,
      score: 72,
      minSpread: "0.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 1,
      regulators: ["CySEC", "FCA", "FSA", "FSCA"],
      established: 2008,
      specialties: ["Multi-Regulated", "Global Presence", "Client Protection"]
    },
    {
      id: "hotforex",
      rank: 15,
      name: "HotForex",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.8,
      score: 70,
      minSpread: "1.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 5,
      regulators: ["CySEC", "FSA", "FSCA", "DFSA"],
      established: 2010,
      specialties: ["Multi-Regulated", "Segregated Funds", "Awards"]
    },
    {
      id: "fxtm",
      rank: 16,
      name: "FXTM",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.6,
      score: 68,
      minSpread: "1.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FCA", "FSA", "FSCA"],
      established: 2011,
      specialties: ["Multi-Regulated", "Global Presence", "Client Protection"]
    },
    {
      id: "alpari",
      rank: 17,
      name: "Alpari",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.4,
      score: 66,
      minSpread: "0.6 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSA", "CySEC", "CRFIN"],
      established: 1998,
      specialties: ["25+ Years", "Multi-Regulated", "Global Presence"]
    },
    {
      id: "roboforex",
      rank: 18,
      name: "RoboForex",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.2,
      score: 64,
      minSpread: "0.0 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FSC", "IFSC"],
      established: 2009,
      specialties: ["Multi-Regulated", "Global Licenses", "Client Protection"]
    },
    {
      id: "fbs",
      rank: 19,
      name: "FBS",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 5.8,
      score: 62,
      minSpread: "0.5 pips",
      maxLeverage: "1:3000",
      minDeposit: 1,
      regulators: ["CySEC", "IFSC", "ASIC"],
      established: 2009,
      specialties: ["Multi-Regulated", "Global Presence", "Awards"]
    },
    {
      id: "instaforex",
      rank: 20,
      name: "InstaForex",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.0,
      score: 60,
      minSpread: "3.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSC", "CySEC", "BVI FSC"],
      established: 2007,
      specialties: ["Multi-Regulated", "Global Presence", "Awards"]
    }
  ],
  execution: [
    {
      id: "ic-markets",
      rank: 1,
      name: "IC Markets",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.6,
      score: 98,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 200,
      regulators: ["ASIC", "CySEC", "FSA"],
      established: 2007,
      specialties: ["True ECN", "0.4ms Latency", "Institutional Liquidity"]
    },
    {
      id: "pepperstone",
      rank: 2,
      name: "Pepperstone",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.2,
      score: 96,
      minSpread: "0.0 pips",
      maxLeverage: "1:400",
      minDeposit: 0,
      regulators: ["ASIC", "FCA", "CySEC", "BaFin"],
      established: 2010,
      specialties: ["Smart Trader Tools", "VPS", "Ultra-Fast Execution"]
    },
    {
      id: "fp-markets",
      rank: 3,
      name: "FP Markets",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.4,
      score: 94,
      minSpread: "0.1 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["ASIC", "CySEC"],
      established: 2005,
      specialties: ["IRESS Platform", "VPS Hosting", "Fast Execution"]
    },
    {
      id: "tickmill",
      rank: 4,
      name: "Tickmill",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.0,
      score: 92,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSA"],
      established: 2014,
      specialties: ["Institutional Liquidity", "ECN", "Low Latency"]
    },
    {
      id: "exness",
      rank: 5,
      name: "Exness",
      logo: "https://images.pexels.com/photos/7567526/pexels-photo-7567526.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.6,
      score: 90,
      minSpread: "0.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 1,
      regulators: ["CySEC", "FCA", "FSA"],
      established: 2008,
      specialties: ["Instant Execution", "Market Execution", "Professional"]
    },
    {
      id: "oanda",
      rank: 6,
      name: "OANDA",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.8,
      score: 88,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 0,
      regulators: ["CFTC", "NFA", "FCA", "ASIC"],
      established: 1996,
      specialties: ["Fractional Units", "No Requotes", "Transparent"]
    },
    {
      id: "admiral-markets",
      rank: 7,
      name: "Admiral Markets",
      logo: "https://images.pexels.com/photos/6802042/pexels-photo-6802042.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.4,
      score: 86,
      minSpread: "0.5 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC"],
      established: 2001,
      specialties: ["MetaTrader Supreme", "VPS", "Fast Execution"]
    },
    {
      id: "forex-com",
      rank: 8,
      name: "Forex.com",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.6,
      score: 84,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 100,
      regulators: ["CFTC", "NFA", "FCA"],
      established: 2001,
      specialties: ["DMA Execution", "Institutional", "Advanced Platform"]
    },
    {
      id: "fxpro",
      rank: 9,
      name: "FxPro",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.2,
      score: 82,
      minSpread: "0.6 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSCA"],
      established: 2006,
      specialties: ["NDD Execution", "cTrader", "Multi-Platform"]
    },
    {
      id: "roboforex",
      rank: 10,
      name: "RoboForex",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.2,
      score: 80,
      minSpread: "0.0 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FSC"],
      established: 2009,
      specialties: ["R Trader", "ECN Execution", "Fast Processing"]
    },
    {
      id: "ig-group",
      rank: 11,
      name: "IG Group",
      logo: "https://images.pexels.com/photos/6802049/pexels-photo-6802049.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.4,
      score: 78,
      minSpread: "0.6 pips",
      maxLeverage: "1:30",
      minDeposit: 250,
      regulators: ["FCA", "ASIC", "MAS"],
      established: 1974,
      specialties: ["DMA", "Advanced Platform", "Professional"]
    },
    {
      id: "xm-group",
      rank: 12,
      name: "XM Group",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.0,
      score: 76,
      minSpread: "1.0 pips",
      maxLeverage: "1:888",
      minDeposit: 5,
      regulators: ["CySEC", "IFSC", "ASIC"],
      established: 2009,
      specialties: ["No Requotes", "99.35% Execution", "Reliable"]
    },
    {
      id: "alpari",
      rank: 13,
      name: "Alpari",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.4,
      score: 74,
      minSpread: "0.6 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSA", "CySEC"],
      established: 1998,
      specialties: ["ECN Execution", "Professional", "Institutional"]
    },
    {
      id: "plus500",
      rank: 14,
      name: "Plus500",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.2,
      score: 72,
      minSpread: "0.7 pips",
      maxLeverage: "1:30",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC", "MAS"],
      established: 2008,
      specialties: ["Proprietary Platform", "Fast Execution", "Reliable"]
    },
    {
      id: "avatrade",
      rank: 15,
      name: "AvaTrade",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.8,
      score: 70,
      minSpread: "0.9 pips",
      maxLeverage: "1:400",
      minDeposit: 100,
      regulators: ["CBI", "ASIC", "FSA", "FSCA"],
      established: 2006,
      specialties: ["Multi-Platform", "Reliable", "Professional"]
    },
    {
      id: "etoro",
      rank: 16,
      name: "eToro",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.0,
      score: 68,
      minSpread: "1.0 pips",
      maxLeverage: "1:30",
      minDeposit: 50,
      regulators: ["CySEC", "FCA", "ASIC"],
      established: 2007,
      specialties: ["Social Trading", "Copy Trading", "User-Friendly"]
    },
    {
      id: "hotforex",
      rank: 17,
      name: "HotForex",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.8,
      score: 66,
      minSpread: "1.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 5,
      regulators: ["CySEC", "FSA", "FSCA"],
      established: 2010,
      specialties: ["Fast Execution", "Multiple Platforms", "Reliable"]
    },
    {
      id: "fxtm",
      rank: 18,
      name: "FXTM",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.6,
      score: 64,
      minSpread: "1.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FCA", "FSA"],
      established: 2011,
      specialties: ["Fast Execution", "Multiple Platforms", "Reliable"]
    },
    {
      id: "fbs",
      rank: 19,
      name: "FBS",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 5.8,
      score: 62,
      minSpread: "0.5 pips",
      maxLeverage: "1:3000",
      minDeposit: 1,
      regulators: ["CySEC", "IFSC"],
      established: 2009,
      specialties: ["Fast Execution", "Multiple Platforms", "High Leverage"]
    },
    {
      id: "instaforex",
      rank: 20,
      name: "InstaForex",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.0,
      score: 60,
      minSpread: "3.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSC", "CySEC"],
      established: 2007,
      specialties: ["Multiple Platforms", "Global Presence", "Contests"]
    }
  ],
  beginners: [
    {
      id: "etoro",
      rank: 1,
      name: "eToro",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.0,
      score: 96,
      minSpread: "1.0 pips",
      maxLeverage: "1:30",
      minDeposit: 50,
      regulators: ["CySEC", "FCA", "ASIC"],
      established: 2007,
      specialties: ["Social Trading", "Copy Trading", "User-Friendly"]
    },
    {
      id: "xm-group",
      rank: 2,
      name: "XM Group",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.0,
      score: 94,
      minSpread: "1.0 pips",
      maxLeverage: "1:888",
      minDeposit: 5,
      regulators: ["CySEC", "IFSC", "ASIC"],
      established: 2009,
      specialties: ["$5 Min Deposit", "Education", "Webinars"]
    },
    {
      id: "pepperstone",
      rank: 3,
      name: "Pepperstone",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.2,
      score: 92,
      minSpread: "0.0 pips",
      maxLeverage: "1:400",
      minDeposit: 0,
      regulators: ["ASIC", "FCA", "CySEC", "BaFin"],
      established: 2010,
      specialties: ["No Min Deposit", "TradingView", "Education"]
    },
    {
      id: "oanda",
      rank: 4,
      name: "OANDA",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.8,
      score: 90,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 0,
      regulators: ["CFTC", "NFA", "FCA", "ASIC"],
      established: 1996,
      specialties: ["No Min Deposit", "Education", "Transparency"]
    },
    {
      id: "plus500",
      rank: 5,
      name: "Plus500",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.2,
      score: 88,
      minSpread: "0.7 pips",
      maxLeverage: "1:30",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC", "MAS"],
      established: 2008,
      specialties: ["Simple Platform", "Demo Account", "User-Friendly"]
    },
    {
      id: "avatrade",
      rank: 6,
      name: "AvaTrade",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.8,
      score: 86,
      minSpread: "0.9 pips",
      maxLeverage: "1:400",
      minDeposit: 100,
      regulators: ["CBI", "ASIC", "FSA", "FSCA"],
      established: 2006,
      specialties: ["Education", "Trading Central", "Webinars"]
    },
    {
      id: "fp-markets",
      rank: 7,
      name: "FP Markets",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.4,
      score: 84,
      minSpread: "0.1 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["ASIC", "CySEC"],
      established: 2005,
      specialties: ["Copy Trading", "Education", "Support"]
    },
    {
      id: "exness",
      rank: 8,
      name: "Exness",
      logo: "https://images.pexels.com/photos/7567526/pexels-photo-7567526.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.6,
      score: 82,
      minSpread: "0.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 1,
      regulators: ["CySEC", "FCA", "FSA"],
      established: 2008,
      specialties: ["$1 Min Deposit", "Instant Withdrawals", "Support"]
    },
    {
      id: "fxtm",
      rank: 9,
      name: "FXTM",
      logo: "https://images.pexels.com/photos/7413915/pexels-photo-7413915.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.6,
      score: 80,
      minSpread: "1.3 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FCA", "FSA"],
      established: 2011,
      specialties: ["Education", "Micro Accounts", "Copy Trading"]
    },
    {
      id: "hotforex",
      rank: 10,
      name: "HotForex",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.8,
      score: 78,
      minSpread: "1.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 5,
      regulators: ["CySEC", "FSA", "FSCA"],
      established: 2010,
      specialties: ["$5 Min Deposit", "Education", "Copy Trading"]
    },
    {
      id: "admiral-markets",
      rank: 11,
      name: "Admiral Markets",
      logo: "https://images.pexels.com/photos/6802042/pexels-photo-6802042.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.4,
      score: 76,
      minSpread: "0.5 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "ASIC"],
      established: 2001,
      specialties: ["Education", "Webinars", "Analytics"]
    },
    {
      id: "ig-group",
      rank: 12,
      name: "IG Group",
      logo: "https://images.pexels.com/photos/6802049/pexels-photo-6802049.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.4,
      score: 74,
      minSpread: "0.6 pips",
      maxLeverage: "1:30",
      minDeposit: 250,
      regulators: ["FCA", "ASIC", "MAS"],
      established: 1974,
      specialties: ["Education", "Research", "Analysis"]
    },
    {
      id: "forex-com",
      rank: 13,
      name: "Forex.com",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 8.6,
      score: 72,
      minSpread: "0.8 pips",
      maxLeverage: "1:50",
      minDeposit: 100,
      regulators: ["CFTC", "NFA", "FCA"],
      established: 2001,
      specialties: ["Education", "Research", "Analysis"]
    },
    {
      id: "alpari",
      rank: 14,
      name: "Alpari",
      logo: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.4,
      score: 70,
      minSpread: "0.6 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSA", "CySEC"],
      established: 1998,
      specialties: ["$1 Min Deposit", "Education", "Analytics"]
    },
    {
      id: "ic-markets",
      rank: 15,
      name: "IC Markets",
      logo: "https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 9.6,
      score: 68,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 200,
      regulators: ["ASIC", "CySEC", "FSA"],
      established: 2007,
      specialties: ["Education", "Support", "Professional"]
    },
    {
      id: "tickmill",
      rank: 16,
      name: "Tickmill",
      logo: "https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.0,
      score: 66,
      minSpread: "0.0 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSA"],
      established: 2014,
      specialties: ["Education", "Support", "Analytics"]
    },
    {
      id: "fxpro",
      rank: 17,
      name: "FxPro",
      logo: "https://images.pexels.com/photos/8370733/pexels-photo-8370733.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 7.2,
      score: 64,
      minSpread: "0.6 pips",
      maxLeverage: "1:500",
      minDeposit: 100,
      regulators: ["FCA", "CySEC", "FSCA"],
      established: 2006,
      specialties: ["Education", "Support", "Multi-Platform"]
    },
    {
      id: "roboforex",
      rank: 18,
      name: "RoboForex",
      logo: "https://images.pexels.com/photos/6801642/pexels-photo-6801642.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.2,
      score: 62,
      minSpread: "0.0 pips",
      maxLeverage: "1:2000",
      minDeposit: 10,
      regulators: ["CySEC", "FSC"],
      established: 2009,
      specialties: ["CopyFX", "Analytics", "Education"]
    },
    {
      id: "fbs",
      rank: 19,
      name: "FBS",
      logo: "https://images.pexels.com/photos/7413892/pexels-photo-7413892.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 5.8,
      score: 60,
      minSpread: "0.5 pips",
      maxLeverage: "1:3000",
      minDeposit: 1,
      regulators: ["CySEC", "IFSC"],
      established: 2009,
      specialties: ["$1 Min Deposit", "Bonuses", "Education"]
    },
    {
      id: "instaforex",
      rank: 20,
      name: "InstaForex",
      logo: "https://images.pexels.com/photos/8370421/pexels-photo-8370421.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
      rating: 6.0,
      score: 58,
      minSpread: "3.0 pips",
      maxLeverage: "1:1000",
      minDeposit: 1,
      regulators: ["FSC", "CySEC"],
      established: 2007,
      specialties: ["$1 Min Deposit", "Contests", "ForexCopy"]
    }
  ]
};